# Generated by Django 4.1.3 on 2022-11-24 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ('first_name', 'last_name', 'username')},
        ),
        migrations.AddField(
            model_name='client',
            name='avatar',
            field=models.ImageField(default='', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='client',
            name='username',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
    ]
