# Generated by Django 4.1.3 on 2022-11-28 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0002_alter_client_options_client_avatar_client_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='avatar',
            field=models.ImageField(default='avatars/default.svg', upload_to='avatars'),
        ),
    ]
