# Generated by Django 4.1.3 on 2022-12-05 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0007_alter_client_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminlog',
            name='products',
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='avatar',
            field=models.ImageField(default='avatars/default.svg', upload_to='avatars/'),
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coreapp.product')),
            ],
        ),
        migrations.AddField(
            model_name='adminlog',
            name='purchase',
            field=models.ManyToManyField(to='coreapp.purchase'),
        ),
    ]
