# Generated by Django 4.1.3 on 2022-12-05 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreapp', '0009_product_is_popular'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
